server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/graduation?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 50
    maxWait: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#params
qipeng:
  name: qipeng
  realname: "username: ${username}"
# wx params
wx:
  appid: wx6220b278ebd18d39
  secret: bc85eee772f5a28a9d97b47bbe9024c8
  url: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=CODE&grant_type=authorization_code