server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://47.94.253.241:3306/graduation?useSSL=false
    username: root
    password: Salanghei210!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#params
qipeng:
  name: qipeng
  realname: "username: ${username}"
# wx params
wx:
  appid: wx6220b278ebd18d39
  secret: bc85eee772f5a28a9d97b47bbe9024c8
  url: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=CODE&grant_type=authorization_code